Repository sparkdotfi/spark-spells, pull requests merged in 2023-09, with the labels that each got.

#14 [SC-89] August 30 spell
  .assets/0925c1769e59aa8980eedd3a749353410d0f81cb.svg
  .assets/6f18d050393b57d378dabab99d1d8e3c987f9745.svg
  .assets/cd81f33cff702ec67039ac122efc6ca918e16284.svg
  archive/20230816/SparkEthereum_20230816.sol
  archive/20230816/SparkEthereum_20230816.t.sol
  archive/20230816/SparkGoerli_20230816.sol
  archive/20230816/SparkGoerli_20230816.t.sol
  diffs/20230830-Ethereum-0xC13e21B648A5Ee794902342038FF3aDAB66BE987-pre_20230830-Ethereum-0xC13e21B648A5Ee794902342038FF3aDAB66BE987-post.md
  src/AaveV3PayloadBase.sol
  src/proposals/20230830/SparkEthereum_20230830.sol
  src/proposals/20230830/SparkEthereum_20230830.t.sol
  src/proposals/20230830/SparkGoerli_20230830.sol
  src/proposals/20230830/SparkGoerli_20230830.t.sol
Labels: Priority: Medium, Status: Ready for Merge

#16 [SC-125] September 13 spell
  .assets/aeff12e76484ee5e37e7f3ef73c75ba1c47d0160.svg
  archive/20230830/SparkEthereum_20230830.sol
  archive/20230830/SparkEthereum_20230830.t.sol
  archive/20230830/SparkGoerli_20230830.sol
  archive/20230830/SparkGoerli_20230830.t.sol
  diffs/20230913-Ethereum-0xC13e21B648A5Ee794902342038FF3aDAB66BE987-pre_20230913-Ethereum-0xC13e21B648A5Ee794902342038FF3aDAB66BE987-post.md
  src/SparkTestBase.sol
  src/proposals/20230913/SparkEthereum_20230913.sol
  src/proposals/20230913/SparkEthereum_20230913.t.sol
  src/proposals/20230913/SparkGoerli_20230913.sol
  src/proposals/20230913/SparkGoerli_20230913.t.sol
Labels: Priority: Medium, Status: Ready to Deploy

#18 [SC-109] Gnosis Chain Activation Spell
  .assets/3dd3c7b6d706dd4cad186206f2468aa0ed6ad111.svg
  .assets/5a65b81770c7a5ded7b2b6b716b42b665917ff0c.svg
  .assets/792b6ff5d783f7c2c05af1bbb77e8fe30c643f13.svg
  .assets/be2a967a00e7dd069085cee401be0869b673f6b6.svg
  .github/workflows/test.yml
  README.md
  archive/20230913/SparkEthereum_20230913.sol
  archive/20230913/SparkEthereum_20230913.t.sol
  archive/20230913/SparkGoerli_20230913.sol
  archive/20230913/SparkGoerli_20230913.t.sol
  diffs/20230927-Ethereum-0xC13e21B648A5Ee794902342038FF3aDAB66BE987-pre_20230927-Ethereum-0xC13e21B648A5Ee794902342038FF3aDAB66BE987-post.md
  diffs/20230927-Gnosis-0x2Dae5307c5E3FD1CF5A72Cb6F698f915860607e0-pre_20230927-Gnosis-0x2Dae5307c5E3FD1CF5A72Cb6F698f915860607e0-post.md
  scripts/cast-spell.sh
  scripts/fork-and-cast-spell.sh
  src/CommonTestBase.sol
  src/ProtocolV3TestBase.sol
  src/SparkPayloadGnosis.sol
  src/SparkTestBase.sol
  src/proposals/20230927/SparkEthereum_20230927.sol
  src/proposals/20230927/SparkEthereum_20230927.t.sol
  src/proposals/20230927/SparkGnosis_20230927.sol
  src/proposals/20230927/SparkGnosis_20230927.t.sol
Labels: Priority: High, Status: Ready for Review
